export const ExerciseImages = {
  1: require("../assets/images/exercises/1.webp"),
  2: require("../assets/images/exercises/2.webp"),
  3: require("../assets/images/exercises/3.webp"),
  4: require("../assets/images/exercises/4.webp"),
  5: require("../assets/images/exercises/5.webp"),
  6: require("../assets/images/exercises/6.webp"),
  7: require("../assets/images/exercises/7.webp"),
  8: require("../assets/images/exercises/8.webp"),
  9: require("../assets/images/exercises/9.webp"),
  10: require("../assets/images/exercises/10.webp"),
  11: require("../assets/images/exercises/11.webp"),
  12: require("../assets/images/exercises/12.webp"),
  13: require("../assets/images/exercises/13.webp"),
  14: require("../assets/images/exercises/14.webp"),
  15: require("../assets/images/exercises/15.webp"),
  16: require("../assets/images/exercises/16.webp"),
  17: require("../assets/images/exercises/17.webp"),
  18: require("../assets/images/exercises/18.webp"),
  19: require("../assets/images/exercises/19.webp"),
  20: require("../assets/images/exercises/20.webp"),
};
